Provides conan file to build artifacts
elear-solutions/sqlite pull request #2
Opened 2019-03-14 17:03 UTC by deekshith-elear

Adds conan recipe file to this repo

2019-04-24 12:29 UTC, manavkumarm requested changes

2019-04-24 12:29 UTC, manavkumarm commented on conanfile.py
> +    options = {"shared": [True, False]}
Fix spacing as per httpserver feedback

2019-04-25 10:07 UTC, deekshith-elear commented on conanfile.py
> +    options = {"shared": [True, False]}
handled

2019-04-25 10:52 UTC, manavkumarm approved these changes

2019-04-25 10:52 UTC, manavkumarm commented on conanfile.py
> +    options = { "shared": [True, False] }
Pending style fix: `[ True, False ]` - space after [, space before ]

2019-04-29 05:38 UTC, deekshith-elear commented on conanfile.py
> +    options = { "shared": [True, False] }
handled

2019-04-29 05:38 UTC, merged